### ISSUE TITLE
Suggestion: allow specifying a file to open

### ISSUE THREAD

**Issue by AckslD** [terror/vim-profiler#1]
It would be great to be able to specify a file to open for cases where certain plugins are lazy loaded on file types.

**Comment by windwp** [comment]
make a GitHub action CI to create profile image  on README

**Comment by terror** [comment]
@AckslD implemented in #2, thanks for the suggestion! I could see it being useful for some.

**Comment by terror** [comment]
> make a GitHub action CI to create profile image on README

Hi @windwp, could you clarify what you mean by this? My initial understanding is a github action that runs vim-profiler and updates the readme with an image? (on vim/neovim plugins)

**Comment by windwp** [comment]
yes it will be nice if that be an image i think svg  is good enough. 
then when i make a commit i can see a starup time change

**Comment by AckslD** [comment]
Awesome @terror, I'll try it out 👍
